### ISSUE TITLE
Color setting not recognized

### ISSUE THREAD

**Issue by OlliZabal** [sschreier/sschreierTopbarnotifications#1]
Thank you for sharing this plugin!

I've installed this plugin on Shopware v6.3.4.1 Stable Version (caching is set off) and noticed, that the color settings are somehow not recognized.

Font-color and icons: always set to #4a545b

Top-bar: background-color is always #fff

Any ideas?

**Comment by OlliZabal** [comment]
Had to re-install via console. Works now fine!

**Comment by sschreier** [comment]
It should be sufficient either to reassign the theme to the SalesChannel or to compile the theme via the console ( bin/console theme:compile ). A re-install is not necessary.
