### ISSUE TITLE
Error: class "Sschreier\TopbarNotifications\SschreierTopbarNotifications" is not found

### ISSUE THREAD

**Issue by OlliZabal** [sschreier/sschreierTopbarnotifications#2]
Can't install the latest version 1.0.2. I get the following error:
`The class "Sschreier\TopbarNotifications\SschreierTopbarNotifications" is not found. Probably an class loader error. Check your plugin composer.json`

Had installed v1.0.1 and removed before updating.

-> Shopware v6.4.1.2 Stable Version

**Comment by sschreier** [comment]
Hello @OlliZabal,

thanks for creating that issue. When I run `git status`, nothing is to commit. On my local machine the name of the file is SschreierTopbarNotifications.php. git does not seem to notice the renaming from sschreierTopbarnotifications.php to SschreierTopbarNotifications.php and therefore did not execute it. I have now done the renaming in the online repository so it works again. Thanks for the feedback.

Best regards

Sebastian
