### ISSUE TITLE
Color changes not visible until theme:compile

### ISSUE THREAD

**Issue by vardumper** [sschreier/sschreierTopbarnotifications#5]
Is there a way to compile one or all themes in the backend? I don't want content editors having to wait for an it guy to compile themes on the CLI.

Alternatively, could or should one add these values as inline styles?

**Comment by sschreier** [comment]
Hello Eric,

you have to compile the theme e.g. via the backend by reassigning the theme (as I described in the readme), then you can see the css changes that you have done in the configuration.

Inline CSS is **never** a good idea - not only because Google (Page Speed) will criticize this.
